# Generated by Django 4.1.6 on 2023-04-29 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='musics/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.album')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.listener')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.track')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.listener')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Listens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_date', models.DateTimeField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.listener')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.track')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zambezimusiccache.musician'),
        ),
    ]
